import streamlit as st
import random

# ------------------------------------------------------------------
# 🎮 THE IMPOSSIBLE NUMBER GUESSER
# Generated by: "GameGenie AI" (It insists this code is perfect)
# ------------------------------------------------------------------

st.set_page_config(page_title="Glitchy Guesser", page_icon="🎮")

st.title("🎮 The Impossible Number Guesser")
st.caption("Can you guess the number between 1 and 100? (Good luck...)")

secret_number = random.randint(1, 100) 

with st.expander("🕵️‍♂️ Developer Debug Info"):
    st.write(f"Current Secret Number: {secret_number}")
    st.write("If this number changes every time you click 'Guess', you have a bug.")

# Input Section
col1, col2 = st.columns(2)
with col1:
    user_guess = st.text_input("Enter your guess here:")

with col2:
    guess_btn = st.button("Submit Guess 🚀")

# Game Logic
if guess_btn and user_guess:
    try:
        guess_int = int(user_guess)
        
        if guess_int == secret_number:
            st.balloons()
            st.success(f"🎉 YOU WON! The number was {secret_number}!")
            
        elif guess_int > secret_number:
            st.warning("📉 Go HIGHER!") 
            
        elif guess_int < secret_number:
            st.warning("📈 Go LOWER!")
            
    except ValueError:
        st.error("That's not a number! Please enter digits only.")

# Footer
st.divider()
st.markdown("*Built with (very confused) AI*")
